# Generated by Django 5.0.4 on 2024-04-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi_app', '0002_alter_history_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='category',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
